{% set version = "3.3.1" %}

package:
  name: palettable
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/palettable/palettable-{{ version }}.tar.gz
  sha256: 3ec242270e4ad045c03d037e5b28f477cc2d0acb7fd59269ad6e0d756acc5ea6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - palettable
    - palettable.cmocean
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.matplotlib
    - palettable.mycarta
    - palettable.tableau
    - palettable.wesanderson

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT
  license_file: license.txt
  summary: Color palettes for Python.

extra:
  recipe-maintainers:
    - ocefpaf
