{% set name = "palettable" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/palettable-{{ version }}.tar.gz
  sha256: 6a867c425a2ff288eab4356bedec00de006dee36c99a6147c2e1b05de789ac9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - palettable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://jiffyclub.github.io/palettable/
  summary: Color palettes for Python
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - ocefpaf
